#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

wmake src/libAtomization

wmake applications/atomizationFoam

# -----------------------------------------------------------------------------
