#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication transformPoints -scale "(0.1 0.1 0.1)"
runApplication topoSet
runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructParMesh
runApplication reconstructPar

